Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/gilded_rose_spec.rb'
    - 'texttest_fixture.rb'
